fork = false
frame = "full"
idle = true
maximized = true
neovim-bin = "/usr/bin/nvim" # in reality found dynamically on $PATH if unset
no-multigrid = false
srgb = false
tabs = true
theme = "auto"
mouse-cursor-icon = "arrow"
title-hidden = true
vsync = false
wsl = false

[font]
normal = [
  "Comic Code Ligatures",
] # Will use the bundled Fira Code Nerd Font by default
size = 12.0
hinting = "full"
edging = "subpixelantialias"
